package updated.mysterium.vpn.exceptions

class ConnectAlreadyExists(message: String) : Exception(message)
